---
title: "Iteration and List Cols"
author: "RuiJun Chen"
date: "10/29/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)
```

## This is gonna be so great

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l
```

```{r}
l$vec_numeric #can use variable names from within list

l$summary

l[[2]] #can use index to pull out things from list; supposed to use 2 sq brackets

mean(l$vec_numeric)
```

```{r}
df = list(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

df$a
df[[2]]

is.list(df)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
mean_and_sd(df[[4]])
```

```{r}
output = vector("list", length = 4) 
```

Write our first for loop!

```{r}
for (i in 1:4) {
  output[[i]] = mean_and_sd(df[[i]])
}

output

output = map(df, mean_and_sd) #for each element within df, runs through mean_and_sd
output

output_median = map(df, median)
output_median

output_summary = map(df, summary)
output_summary

output_median = map_dbl(df, median) #makes output a single list of doubles
output = map_dfr(df, mean_and_sd) #joins output into dataframe

output = map(df, ~mean_and_sd(.x)) #being very explicit about what is being mapped
```

## Napoleon!!


```{r}
read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5) #Adds 1-5 to end of url_base

vec_urls

read_page_reviews(vec_urls[[1]])

output = vector("list", length = 5) #if don't explicitly creates output list, R will try to figure out what it needs. However, R also creates new output for each iteration, copies it over and adds to it, can be slow

for (i in 1:5) {
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

output

output = map(vec_urls, read_page_reviews)
output
```

## list columns / weather df

```{r weather_create, cache = TRUE}
weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

nest within stations

```{r}
weather_nest = 
  weather %>% 
  nest(data = date:tmin) #data has 3:prcp, tmin, tmax for each date (366 x 4)

weather_nest
```

is the list column really a list??

```{r}
weather_nest %>% pull(name)
weather_nest %>% pull(data)

weather_nest$data[[1]]

weather_nest %>% 
  unnest()
```

## Operations on list columns

can I do useful things with a list column...?

```{r}
central_park_df = weather_nest$data[[1]]

lm(tmax ~ tmin, data = central_park_df)

lm(tmax ~ tmin, data = weather_nest$data[[1]])
lm(tmax ~ tmin, data = weather_nest$data[[2]])
lm(tmax ~ tmin, data = weather_nest$data[[3]])

```

try a loop...

```{r}
output = vector("list", length = 3)

for (i in 1:3) {
  output[[i]] = lm(tmax ~ tmin, weather_nest$data[[i]])
}

output
```

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}
```

```{r}
for (i in 1:3) {
  output[[i]] = weather_lm(weather_nest$data[[i]])
}
output

output = map(weather_nest$data, weather_lm)
output
```

```{r}
weather_nest %>% 
  mutate(lin_models = map(data, weather_lm))
```

```{r}
weather_nest %>% 
  mutate(lin_models = map(data, weather_lm)) %>% 
  select(-data) %>% 
  filter(name != "CentralPark_NY")
```

## Revisit Napoleon.. again

```{r}
napoleon = 
  tibble(
    page = 1:5,
    urls = str_c(url_base, page)
  ) %>% 
  mutate(
    reviews = map(urls, read_page_reviews)
  )
napoleon
```

```{r}
napoleon = 
  tibble(
    page = 1:5,
    urls = str_c(url_base, page)
  ) %>% 
  mutate(
    reviews = map(urls, read_page_reviews)
  ) %>% 
  unnest(reviews) %>% 
  select(-urls)

napoleon
```

